prd:
  catalog_name: mlops_prd
  schema_name: telco_churn
acc:
  catalog_name: mlops_stg
  schema_name: telco_churn
dev:
  catalog_name: mlops_dev
  schema_name: telco_churn


experiment_name_basic: /Shared/telco_churn_base
experiment_name_custom: /Shared/telco_churn_custom

parameters:
  n_estimators: 249
  learning_rate: 0.010101614554456295
  num_leaves: 47
  max_depth: 3
  min_child_samples: 50
  subsample: 0.8181523124165577
  colsample_bytree: 0.6246844197312816
  scale_pos_weight: 1.78510483023539


num_features:
  - tenure
  - MonthlyCharges
  - TotalCharges

cat_features:
  - customerID
  - SeniorCitizen
  - Partner
  - Dependents
  - PhoneService
  - PaperlessBilling
  - MultipleLines
  - TechSupport
  - Contract
  - Churn

binary_features:
  - SeniorCitizen
  - Partner
  - Dependents
  - PhoneService
  - PaperlessBilling
  - Churn

target: Churn